import React from 'react';
import type { VerdictData, TokenUsageData, FactCheck } from '../types';

const formatDuration = (ms: number): string => {
  if (ms < 1000) return `${ms}ms`;
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  if (minutes === 0) return `${seconds}s`;
  return `${minutes}m ${remainingSeconds}s`;
};

const formatNumber = (n: number): string => n.toLocaleString();

interface DebateExporterProps {
  data: VerdictData;
  topic: string;
  proponentConfig: { profile: string; tone: string; language: string };
  opponentConfig: { profile: string; tone: string; language: string };
  messages: Array<{ speaker: string; content: string }>;
  tokenUsage: TokenUsageData | null;
  totalWallTimeMs: number | null;
  agentNames?: { proponent: string; opponent: string } | null;
  factChecks?: FactCheck[] | null;
  proLabel: string;
  oppLabel: string;
  winnerName: string;
  onSave?: () => void;
  onRestart: () => void;
}

export const DebateExporter: React.FC<DebateExporterProps> = ({
  data,
  topic,
  proponentConfig,
  opponentConfig,
  messages,
  tokenUsage,
  totalWallTimeMs,
  agentNames,
  factChecks,
  proLabel,
  oppLabel,
  winnerName,
  onSave,
  onRestart,
}) => {
  const [isEmailing, setIsEmailing] = React.useState(false);

  const handleSaveMarkdown = () => {
    const proTotal = data.scores.proponent.logic + data.scores.proponent.evidence + data.scores.proponent.style;
    const oppTotal = data.scores.opponent.logic + data.scores.opponent.evidence + data.scores.opponent.style;
    const date = new Date().toLocaleString();

    let md = `# AgonAI Debate Report\n\n`;
    md += `**Date:** ${date}\n\n`;
    md += `**Topic:** ${topic}\n\n`;
    md += `---\n\n`;

    md += `## Agent Configuration\n\n`;
    md += `| | ${proLabel} (Proponent) | ${oppLabel} (Opponent) |\n`;
    md += `|---|---|---|\n`;
    md += `| Profile | ${proponentConfig.profile} | ${opponentConfig.profile} |\n`;
    md += `| Tone | ${proponentConfig.tone} | ${opponentConfig.tone} |\n`;
    md += `| Language | ${proponentConfig.language} | ${opponentConfig.language} |\n\n`;

    md += `---\n\n`;
    md += `## Debate Transcript\n\n`;

    messages.forEach((msg) => {
      const speaker = msg.speaker.toLowerCase();
      let label = msg.speaker;
      if (speaker.includes('proponent')) label = `${proLabel} (Proponent)`;
      else if (speaker.includes('opponent')) label = `${oppLabel} (Opponent)`;
      else if (speaker.includes('moderator')) label = 'Moderator';
      md += `**${label}:**\n\n${msg.content}\n\n---\n\n`;
    });

    md += `## Verdict\n\n`;
    md += `**Winner: ${winnerName}**\n\n`;

    md += `### Scores\n\n`;
    md += `| Criteria | ${proLabel} | ${oppLabel} |\n`;
    md += `|---|---|---|\n`;
    md += `| Logic | ${data.scores.proponent.logic}/10 | ${data.scores.opponent.logic}/10 |\n`;
    md += `| Evidence | ${data.scores.proponent.evidence}/10 | ${data.scores.opponent.evidence}/10 |\n`;
    md += `| Style | ${data.scores.proponent.style}/10 | ${data.scores.opponent.style}/10 |\n`;
    md += `| **Total** | **${proTotal}/30** | **${oppTotal}/30** |\n\n`;

    md += `### Moderator's Rationale\n\n`;
    md += `${data.reasoning}\n\n`;

    if (data.recommendations?.length) {
      md += `### Further Reading\n\n`;
      data.recommendations.forEach((rec) => { md += `- ${rec}\n`; });
      md += `\n`;
    }

    if (data.references?.length) {
      md += `### Sources Cited\n\n`;
      data.references.forEach((ref) => { md += `- ${ref}\n`; });
      md += `\n`;
    }

    if (factChecks?.length) {
      md += `---\n\n## Fact-Check Report\n\n`;
      md += `| Claim | Speaker | Verdict | Explanation |\n`;
      md += `|---|---|---|---|\n`;
      factChecks.forEach((fc) => {
        md += `| ${fc.claim} | ${fc.speaker} | ${fc.verdict} | ${fc.explanation} |\n`;
      });
      md += `\n`;
    }

    if (tokenUsage) {
      md += `---\n\n## Performance Stats\n\n`;
      md += `- **Total Time:** ${formatDuration(totalWallTimeMs ?? tokenUsage.total_duration_ms)}\n`;
      md += `- **LLM Calls:** ${tokenUsage.calls.length}\n`;
      md += `- **Total Tokens:** ${formatNumber(tokenUsage.total_input_tokens + tokenUsage.total_output_tokens)} (${formatNumber(tokenUsage.total_input_tokens)} in / ${formatNumber(tokenUsage.total_output_tokens)} out)\n`;
      md += `- **API Processing:** ${formatDuration(tokenUsage.total_duration_ms)}\n`;
      md += `\n`;
    }

    md += `---\n\n*Generated by [AgonAI](https://github.com/michaelnce/AgonAI)*\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const slug = topic.slice(0, 40).replace(/[^a-zA-Z0-9]+/g, '-').replace(/-+$/, '').toLowerCase();
    a.href = url;
    a.download = `agonai-debate-${slug}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleSendEmail = async () => {
    const email = window.prompt("Enter recipient email address:");
    if (!email) return;

    setIsEmailing(true);
    try {
      const response = await fetch('/api/debate/email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          recipient_email: email,
          topic,
          proponent: proponentConfig,
          opponent: opponentConfig,
          messages,
          verdict: data,
          token_usage: tokenUsage,
          total_wall_time_ms: totalWallTimeMs,
          agent_names: agentNames,
          fact_checks: factChecks,
        }),
      });

      if (response.ok) {
        alert("Email sent successfully!");
      } else {
        const err = await response.json();
        const errorMessage = typeof err.detail === 'string' ? err.detail : JSON.stringify(err.detail, null, 2);
        alert("Failed to send email: " + (errorMessage || "Unknown error"));
      }
    } catch (e) {
      alert("Error sending email: " + String(e));
    } finally {
      setIsEmailing(false);
    }
  };

  return (
    <div className="p-4 bg-[#1E293B] border-t border-gray-700 flex flex-wrap justify-center gap-3 md:gap-4">
      {onSave && (
        <button onClick={onSave} className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold px-6 py-2 rounded-lg text-sm transition-colors shadow-lg">
          Save Debate
        </button>
      )}
      <button onClick={handleSaveMarkdown} className="bg-cyan-600 hover:bg-cyan-700 text-white font-bold px-6 py-2 rounded-lg text-sm transition-colors shadow-lg">
        Save as MD
      </button>
      <button onClick={handleSendEmail} disabled={isEmailing} className="bg-amber-600 hover:bg-amber-700 disabled:opacity-50 text-white font-bold px-6 py-2 rounded-lg text-sm transition-colors shadow-lg">
        {isEmailing ? 'Sending...' : 'Send Summary'}
      </button>
      <button onClick={onRestart} className="bg-blue-600 hover:bg-blue-700 text-white font-bold px-6 py-2 rounded-lg text-sm transition-colors shadow-lg">
        Reset Arena
      </button>
    </div>
  );
};
